name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'   # change if you use another version

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install dependencies
        # Install project dependencies; ensure your requirements.txt is up to date.
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          # install dev/test tools (pytest, requests, fastapi for TestClient)
          pip install -r requirements-dev.txt

      - name: Run tests
        run: |
          pytest -q
